metrics:
  bstats: true

models:
  namespace: "modelengine"
  join-send-delay: 500 # ms
  spawn-send-delay: 50 # ms
  properties-send-delay: 30 # ms
  entity-position-update-period: 35 # ms
  thread-pool-size: 4
  respawn-resend-delay: 20 # tick, 玩家 respawn/换维度后延迟多久重发模型载体(等客户端实体系统 resync 就绪)

options:
  debug:
    spawn: false
    animations: false
    send-data: false
    location: false
    death: false
  hooks:
    floodgate: true # Recommended method